instrumentation-test:
  needs: [ unit-test ]
  runs-on: macos-latest
  steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Run espresso tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 28
        target: google_apis
        arch: x86_64
        profile: Nexus 6
        avd-name: test
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        emulator-boot-timeout: 600
        script: |
          adb devices
          adb shell getprop sys.boot_completed
          ./gradlew connectedCheck --stacktrace

    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: instrumentation_test_report
        path: app/build/reports/androidTests/connected/