name: Android CI/CD

on:
  push:
    branches:
      - dev
      - master  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Grant execute permission for Gradlew
      run: chmod +x gradlew

    - name: Run linting
      run: ./gradlew lintDebug

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest

    - name: Run instrumentation tests
      run: ./gradlew connectedDebugAndroidTest

    - name: Generate code coverage report
      run: ./gradlew jacocoTestReport

    - name: Upload code coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: app/build/reports/jacoco/jacocoTestReport/html/index.html

    - name: Build release APK
      run: ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk
